version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb_neo
    ports:
      - "27017:27017"
    networks:
      - my_network

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - my_network
    tmpfs:
      - /var/lib/neo4j/run

networks:
  my_network:
    driver: bridge